### ISSUE TITLE
User Story Checklist

### ISSUE THREAD

**Issue by srandle93** [srandle93/Group_Project_1#2]
## User Story
 As a user, I want to see questions that I can choose an answer to. 

## Acceptance Criteria
- [ ] Create a `div` to place questions on the website.
- [ ] Create onClick button to make API call to display question.
- [ ] Print question to the `div` that we created previously.
- [ ] Create `form` for user to answer question.

**Comment by anh0238** [comment]
## User Story
As a user, I want to see my score being tracked.

## Acceptance Criteria
- [] create `div` for score to display in
- [] determine if the question was answered correctly
- [] `if/else` -- if answer is correct `score++`, else tell user the answer is incorrect (look into modals, not alerts)
- [] print score in the `div`
