### ISSUE TITLE
User Story - Score Tracking

### ISSUE THREAD

**Issue by anh0238** [srandle93/Group_Project_1#6]
## User Story
As a user, I want to see my score being tracked.

## Acceptance Criteria
- [] create `div` for score to display in
- [] determine if the question was answered correctly
- [] `if/else` -- if answer is correct `score++`, else tell user the answer is incorrect (look into modals, not alerts)
- [] print score in the `div`
